In [ ]:
"""
numpy.linspace() function is used to create an array of evenly spaced numbers over a specified range. 

It takes three parameters: start, stop, and num. 
    The start parameter specifies the starting value of the sequence
    The stop parameter specifies the end value of the sequence
    The num parameter specifies the number of evenly spaced values to generate between start and stop.
"""

"""
np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    start: The starting value of the sequence.
    stop: The end value of the sequence.
    num: The number of evenly spaced samples to generate. Default is 50.
    endpoint: If True (default), stop is the last sample. Otherwise, it is not included.
    retstep: If True, return the step size between samples. Default is False.
    dtype: The data type of the output array. If None, the data type is inferred from the input.
"""

import numpy as np

# Create an array of 5 evenly spaced values between 0 and 1, including the endpoint
arr1 = np.linspace(0, 1, num=5)
print("Array with 5 evenly spaced values between 0 and 1:")
print(arr1) # [0.   0.25  0.5   0.75 1. ]

# Create an array of 5 evenly spaced values between 0 and 1, excluding the endpoint
arr2 = np.linspace(0, 1, num=5, endpoint=False)
print("\nArray with 5 evenly spaced values between 0 and 1 (excluding endpoint):")
print(arr2) # [0.  0.2 0.4 0.6 0.8]

# Create an array of 5 evenly spaced values between 0 and 1, including the endpoint, and return the step size
arr3, step = np.linspace(0, 1, num=5, retstep=True)
print("\nArray with 5 evenly spaced values between 0 and 1 (including endpoint) and step size:")
print(arr3) # [0.   0.25  0.5   0.75 1. ]
print("Step size:", step) # Step size: 0.25

In [ ]:
"""
numpy.zeros() function is used to create an array filled with zeros.
"""

"""
np.zeros(shape, dtype=float, order='C')
    shape: The shape of the array to be created. It can be an integer or a tuple of integers.
    dtype: The data type of the output array. Default is float.
    order: The memory layout of the array. 'C' means row-major (C-style) order, and 'F' means column-major (Fortran-style) order. Default is 'C'.
"""

import numpy as np

# Create a 1D array of zeros with length 5
arr4 = np.zeros(5)
print("\n1D array of zeros with length 5:")
print(arr4) # [0. 0. 0. 0. 0.]

# Create a 2D array of zeros with shape (3, 4)
arr5 = np.zeros((3, 4))
print("\n2D array of zeros with shape (3, 4):")
print(arr5)
# [[0. 0. 0. 0.]
#  [0. 0. 0. 0.]
#  [0. 0. 0. 0.]]


arr6 = np.zeros((2, 3), dtype=int)
print("\n2D array of zeros with shape (2, 3):")
print(arr6)
# [[0 0 0]
#  [0 0 0]]

In [ ]:
"""
numpy.ones() function is used to create an array filled with ones.
"""

"""
np.ones(shape, dtype=float, order='C')
    shape: The shape of the array to be created. It can be an integer or a tuple of integers.
    dtype: The data type of the output array. Default is float.
    order: The memory layout of the array. 'C' means row-major (C-style) order, and 'F' means column-major (Fortran-style) order. Default is 'C'.
"""

import numpy as np

# Create a 1D array of ones with length 5
arr7 = np.ones(5)
print("\n1D array of ones with length 5:")
print(arr7) # [1. 1. 1. 1. 1.]

# Create a 2D array of ones with shape (3, 4)
arr8 = np.ones((3, 4))
print("\n2D array of ones with shape (3, 4):")
print(arr8)
# [[1. 1. 1. 1.]
#  [1. 1. 1. 1.]
#  [1. 1. 1. 1.]]

arr9 = np.ones((2, 3), dtype=int)
print("\n2D array of ones with shape (2, 3):")
print(arr9)
# [[1 1 1]
#  [1 1 1]]

In [ ]:
"""
numpy.random.rand() function is used to create an array of random numbers drawn from a uniform distribution over [0, 1).
"""

"""
np.random.rand(d0, d1, ..., dn)
    d0, d1, ..., dn: The dimensions of the output array. Each dimension is specified as an integer. The function will generate random numbers in the range [0, 1) for each element of the array.
"""

import numpy as np

# Create a single random number between 0 and 1
arr10 = np.random.rand()
print("\nSingle random number between 0 and 1:")
print(arr10) # e.g., 0.5488135039273248

# Create a 1D array of 5 random numbers between 0 and 1
arr11 = np.random.rand(5)
print("\n1D array of 5 random numbers between 0 and 1:")
print(arr11) # e.g., [0.71518937 0.60276338 0.54488318 0.4236548  0.64589411]

# Create a 2D array of random numbers with shape (3, 4)
arr12 = np.random.rand(3, 4)
print("\n2D array of random numbers with shape (3, 4):")
print(arr12)
# e.g.,
# [[0.43758721 0.891773   0.96366276 0.38344152]
#  [0.79172504 0.52889492 0.56804456 0.92559664]
#  [0.07103606 0.0871293  0.0202184  0.83261985]]  


"""
np.random.randn(d0, d1, ..., dn) generates an array of random numbers drawn from a standard normal distribution (mean = 0, standard deviation = 1).
    d0, d1, ..., dn: The dimensions of the output array. Each dimension is specified as an integer. The function will generate random numbers from a standard normal distribution (mean = 0, standard deviation = 1) for each element of the array.
"""

"""
np.random.randint(low, high=None, size=None, dtype=int) generates an array of random integers drawn from a uniform distribution over the specified range [low, high).
    low: The lowest (inclusive) integer to be drawn from the distribution.
    high: The highest (exclusive) integer to be drawn from the distribution. If None, then the range is [0, low).
    size: The shape of the output array. If None, a single integer is returned.
    dtype: The data type of the output array. Default is int.
"""